import Foundation

struct BankQuestion {
    let category: String
    let text: String
}

enum StaticQuestionBank {
    static let all: [BankQuestion] = [
        .init(category: "fun", text: "What's the weirdest food combo you secretly love?"),
        .init(category: "fun", text: "If we swapped jobs for a week, what would you do first?"),
        .init(category: "fun", text: "Which fictional couple do you think we're most like?"),
        .init(category: "fun", text: "What's a song that instantly reminds you of me?"),
        .init(category: "fun", text: "If you could teleport us anywhere for dinner tonight, where would we eat?"),
        .init(category: "fun", text: "What's the silliest thing you've ever googled?"),
        .init(category: "fun", text: "Which of my habits do you find secretly adorable?"),
        .init(category: "fun", text: "If our relationship had a slogan, what would it be?"),
        .init(category: "fun", text: "What movie could you rewatch with me a hundred times?"),
        .init(category: "fun", text: "What would our pet's name be if it matched my personality?"),
        .init(category: "fun", text: "What's a trend you hope never comes back?"),
        .init(category: "fun", text: "If you won the lottery tomorrow, what's the first silly thing you'd buy?"),
        .init(category: "fun", text: "What's your favorite photo of us and why?"),
        .init(category: "fun", text: "Which emoji do you think describes me best?"),
        .init(category: "fun", text: "What's the most embarrassing thing you've done to impress someone?"),
        .init(category: "fun", text: "If we were a sitcom, what would tonight's episode be called?"),
        .init(category: "fun", text: "What's a talent you wish you had?"),
        .init(category: "fun", text: "What's your go-to karaoke song, be honest?"),
        .init(category: "fun", text: "If you could have dinner with any three people, dead or alive, who's coming?"),
        .init(category: "fun", text: "What's the funniest misunderstanding we've ever had?"),
        .init(category: "fun", text: "What's a smell that instantly takes you back to childhood?"),
        .init(category: "fun", text: "Which app on your phone would surprise me most?"),
        .init(category: "fun", text: "What's the best gift you've ever received — and the worst?"),
        .init(category: "fun", text: "If you had to eat one cuisine forever, which one?"),
        .init(category: "fun", text: "What's something you pretended to understand for way too long?"),
        .init(category: "fun", text: "Which fictional world would you actually want to live in?"),
        .init(category: "fun", text: "What's your most irrational fear?"),
        .init(category: "fun", text: "What would you do with a completely free day, no obligations?"),
        .init(category: "fun", text: "What's the strangest compliment you've ever received?"),
        .init(category: "fun", text: "If we made a band, what would it be called and what would you play?"),

        .init(category: "deep", text: "What's something you've changed your mind about in the last year?"),
        .init(category: "deep", text: "When do you feel most understood by me?"),
        .init(category: "deep", text: "What does a perfect ordinary Tuesday look like for you?"),
        .init(category: "deep", text: "What's a fear you've never said out loud?"),
        .init(category: "deep", text: "Who shaped the way you love the most?"),
        .init(category: "deep", text: "What part of your day do you wish I could see?"),
        .init(category: "deep", text: "What's something you're proud of that you rarely mention?"),
        .init(category: "deep", text: "When you're stressed, what do you need more — space or closeness?"),
        .init(category: "deep", text: "What's a boundary you wish you'd set sooner in life?"),
        .init(category: "deep", text: "What does home mean to you?"),
        .init(category: "deep", text: "What's the kindest thing anyone has ever done for you?"),
        .init(category: "deep", text: "What lesson took you the longest to learn?"),
        .init(category: "deep", text: "What do you hope people feel when they're around you?"),
        .init(category: "deep", text: "What's a dream you've quietly held onto?"),
        .init(category: "deep", text: "How do you want us to fight — what feels fair to you?"),
        .init(category: "deep", text: "What's something you forgive yourself for still working on?"),
        .init(category: "deep", text: "Which compliment do you have the hardest time accepting?"),
        .init(category: "deep", text: "What did you need to hear as a kid that you never did?"),
        .init(category: "deep", text: "When was the last time you cried, and what moved you?"),
        .init(category: "deep", text: "What does trust look like to you in small everyday moments?"),
        .init(category: "deep", text: "What's a story about you I've never heard?"),
        .init(category: "deep", text: "What part of growing up do you miss the most?"),
        .init(category: "deep", text: "What's something you want to unlearn?"),
        .init(category: "deep", text: "How has love changed your definition of it?"),
        .init(category: "deep", text: "What do you think our relationship teaches you about yourself?"),
        .init(category: "deep", text: "What's a moment with me you replay in your head?"),
        .init(category: "deep", text: "What are you most afraid of losing?"),
        .init(category: "deep", text: "What brings you peace when everything feels heavy?"),
        .init(category: "deep", text: "What's a promise you made yourself this year?"),
        .init(category: "deep", text: "What do you want your life to feel like at 70?"),

        .init(category: "future", text: "Where should we go for our next trip — first city that comes to mind?"),
        .init(category: "future", text: "What's one tradition you'd love us to start?"),
        .init(category: "future", text: "What does your dream kitchen look like?"),
        .init(category: "future", text: "How do you picture a perfect Sunday with us five years from now?"),
        .init(category: "future", text: "What's a skill you'd love for us to learn together?"),
        .init(category: "future", text: "What kind of home would make you feel settled?"),
        .init(category: "future", text: "What's a place you want to show me from your past?"),
        .init(category: "future", text: "What's one thing you want us to save up for?"),
        .init(category: "future", text: "How would you spend a whole month with no work, just us?"),
        .init(category: "future", text: "What anniversary celebration would mean the most to you?"),
        .init(category: "future", text: "What's a small goal you want to hit this season?"),
        .init(category: "future", text: "What would make next year our best one yet?"),
        .init(category: "future", text: "If we moved anywhere, where would you choose and why?"),
        .init(category: "future", text: "What's a bucket list item you want us to cross off together?"),
        .init(category: "future", text: "What kind of parents or mentors do you want to be someday?"),
        .init(category: "future", text: "What's a habit you'd love us to build as a team?"),
        .init(category: "future", text: "Where do you want to be when you retire — beach, mountains, city?"),
        .init(category: "future", text: "What's a meal you want us to learn to cook perfectly?"),
        .init(category: "future", text: "What would your ideal birthday with me look like?"),
        .init(category: "future", text: "What's one thing you hope never changes between us?"),
        .init(category: "future", text: "What would you name our future home?"),
        .init(category: "future", text: "What's a dream you have that you haven't told me yet?"),
        .init(category: "future", text: "How can I support your career goals better?"),
        .init(category: "future", text: "What's a book or show you want us to experience together?"),
        .init(category: "future", text: "What family traditions from your childhood do you want to keep?"),
        .init(category: "future", text: "What's your vision of growing old with someone?"),
        .init(category: "future", text: "What's one risk you'd take if you knew I'd back you up?"),
        .init(category: "future", text: "What would a perfect holiday season look like for us?"),
        .init(category: "future", text: "What's something you want us to do while we're still young?"),
        .init(category: "future", text: "If we renewed our vows someday, what would yours say?"),

        .init(category: "intimacy", text: "What's your favorite way to be comforted after a hard day?"),
        .init(category: "intimacy", text: "What small gesture makes you feel the most loved?"),
        .init(category: "intimacy", text: "When did you first know you were falling for me?"),
        .init(category: "intimacy", text: "What's a moment when you felt closest to me?"),
        .init(category: "intimacy", text: "What makes you feel most appreciated that I might not realize?"),
        .init(category: "intimacy", text: "What's your love language today — has it changed?"),
        .init(category: "intimacy", text: "What's something I do that instantly makes you smile?"),
        .init(category: "intimacy", text: "What do you miss most about me when we're apart?"),
        .init(category: "intimacy", text: "What's a memory of us you'd relive if you could?"),
        .init(category: "intimacy", text: "How do you like to be kissed — quick and playful, or slow and lingering?"),
        .init(category: "intimacy", text: "What's the most romantic thing I've ever done?"),
        .init(category: "intimacy", text: "What helps you feel safe opening up to me?"),
        .init(category: "intimacy", text: "What's a vulnerable thing you'd like to tell me?"),
        .init(category: "intimacy", text: "What does physical affection mean to you on ordinary days?"),
        .init(category: "intimacy", text: "What's a compliment from me you'd love to hear more often?"),
        .init(category: "intimacy", text: "When do you feel most beautiful or handsome with me?"),
        .init(category: "intimacy", text: "What's your favorite part of our bedtime routine?"),
        .init(category: "intimacy", text: "What would make our mornings together sweeter?"),
        .init(category: "intimacy", text: "What's something you want us to try together — big or small?"),
        .init(category: "intimacy", text: "What do you think is our song, and what moment made it ours?"),
        .init(category: "intimacy", text: "How can I make you feel more desired?"),
        .init(category: "intimacy", text: "What's a fear you have about us that I can help with?"),
        .init(category: "intimacy", text: "What's your favorite photo of just the two of us?"),
        .init(category: "intimacy", text: "What does commitment mean to you in daily life?"),
        .init(category: "intimacy", text: "What's one way we could deepen our connection this month?"),
        .init(category: "intimacy", text: "What did you think of me before we ever talked?"),
        .init(category: "intimacy", text: "What's a secret dream date you've never told me about?"),
        .init(category: "intimacy", text: "What makes an apology feel real to you?"),
        .init(category: "intimacy", text: "What do you need from me when you're sad?"),
        .init(category: "intimacy", text: "What's the quietest way I show you love that you've noticed?"),

        .init(category: "gratitude", text: "What's something I did this week that you appreciated?"),
        .init(category: "gratitude", text: "What's a way I've grown since we met that you admire?"),
        .init(category: "gratitude", text: "What's the nicest thing I've said to you lately?"),
        .init(category: "gratitude", text: "What everyday thing do I do that you're grateful for?"),
        .init(category: "gratitude", text: "What's a sacrifice I made that meant more than I knew?"),
        .init(category: "gratitude", text: "What do you appreciate about how I handle stress?"),
        .init(category: "gratitude", text: "What's something about my family you're thankful for?"),
        .init(category: "gratitude", text: "What's a hard season we got through that made us stronger?"),
        .init(category: "gratitude", text: "What quality of mine are you most grateful exists?"),
        .init(category: "gratitude", text: "What's a time I made you laugh when you needed it most?"),
        .init(category: "gratitude", text: "What do you feel lucky to have with me?"),
        .init(category: "gratitude", text: "What's something you never thanked me for properly?"),
        .init(category: "gratitude", text: "What do I bring into your life that was missing before?"),
        .init(category: "gratitude", text: "What's a small moment from this week you're thankful for?"),
        .init(category: "gratitude", text: "Who in our lives are you most grateful we met together?"),
        .init(category: "gratitude", text: "What's one thing your body allowed you to do this week that you're grateful for?"),
        .init(category: "gratitude", text: "What's a friendship in your life worth celebrating?"),
        .init(category: "gratitude", text: "What part of your daily routine actually brings you joy?"),
        .init(category: "gratitude", text: "What's something beautiful you noticed today?"),
        .init(category: "gratitude", text: "What's an opportunity you're glad you didn't pass up?"),
        .init(category: "gratitude", text: "What's a mistake you're now grateful you made?"),
        .init(category: "gratitude", text: "What about this season of life are you enjoying most?"),
        .init(category: "gratitude", text: "What's a skill or gift of yours you're finally appreciating?"),
        .init(category: "gratitude", text: "What's something kind a stranger did for you once?"),
        .init(category: "gratitude", text: "What comfort are you most grateful for right now?"),
        .init(category: "gratitude", text: "What's a piece of advice you're thankful someone gave you?"),
        .init(category: "gratitude", text: "What's your favorite thing about our home or space?"),
        .init(category: "gratitude", text: "What's something we have now that we only dreamed of a year ago?"),
        .init(category: "gratitude", text: "Who believed in you before you believed in yourself?"),
        .init(category: "gratitude", text: "What's the best part of loving me? Pick just one — I dare you."),

        .init(category: "fun", text: "What's your hottest take that never fails to start a debate?"),
        .init(category: "fun", text: "If we could only communicate in movie quotes for a day, how would it go?"),
        .init(category: "fun", text: "What's your most controversial pizza topping opinion?"),
        .init(category: "fun", text: "Which of us would survive longest in a zombie movie?"),
        .init(category: "fun", text: "What's the last thing you laughed at until you cried?"),
        .init(category: "fun", text: "If you could instantly master any instrument, which one?"),
        .init(category: "fun", text: "What's a fashion phase you're glad photos of don't exist for?"),
        .init(category: "fun", text: "What's your walkout song if life had entrances?"),
        .init(category: "fun", text: "What conspiracy theory do you half-believe?"),
        .init(category: "fun", text: "If our dog could talk, what would it snitch about you?"),

        .init(category: "deep", text: "What does a good apology sound like to you?"),
        .init(category: "deep", text: "What value do you hope we never compromise on?"),
        .init(category: "deep", text: "What's a moment you're still processing from this year?"),
        .init(category: "deep", text: "How do you want to be remembered by the people you love?"),
        .init(category: "deep", text: "What's the bravest thing you've ever done?"),
        .init(category: "deep", text: "What do you do with loneliness when it visits?"),
        .init(category: "deep", text: "What's a question you wish someone would ask you?"),
        .init(category: "deep", text: "What does rest look like when your mind won't stop?"),
        .init(category: "deep", text: "What's something about your culture you want to pass on?"),
        .init(category: "deep", text: "What advice would you give your younger self about love?"),

        .init(category: "future", text: "What's the first thing you'd want us to do if you got a new job in another city?"),
        .init(category: "future", text: "How many pillows is the right number of pillows? Asking for our future couch."),
        .init(category: "future", text: "What's a date idea you want to steal from a movie?"),
        .init(category: "future", text: "What would our dream roadside road trip playlist sound like?"),
        .init(category: "future", text: "What's something we should do every year on the same day?"),
        .init(category: "future", text: "What's one way we can make our next apartment or house feel more like us?"),
        .init(category: "future", text: "What kind of neighbors do you hope we become?"),
        .init(category: "future", text: "What's a photo you want us to take this year?"),
        .init(category: "future", text: "What's a financial goal that would make you feel safe?"),
        .init(category: "future", text: "What does 'we made it' look like to you?"),

        .init(category: "intimacy", text: "What's your favorite kind of hug — tight and long, or soft and brief?"),
        .init(category: "intimacy", text: "What's a look I give you that you can read instantly?"),
        .init(category: "intimacy", text: "What's something you find attractive about me that isn't physical?"),
        .init(category: "intimacy", text: "What's your ideal slow morning with me?"),
        .init(category: "intimacy", text: "What's a promise you want me to keep forever?"),
        .init(category: "intimacy", text: "What kind of touch do you crave most after a long week?"),
        .init(category: "intimacy", text: "What's a nickname you wish I'd call you?"),
        .init(category: "intimacy", text: "What's the best 'good morning' I could send you?"),
        .init(category: "intimacy", text: "What's something we used to do early on that you miss?"),
        .init(category: "intimacy", text: "What does feeling chosen mean to you?"),

        .init(category: "gratitude", text: "What's my superpower, in your opinion?"),
        .init(category: "gratitude", text: "What's the best decision we've made as a couple?"),
        .init(category: "gratitude", text: "What's something you were wrong about about me at first?"),
        .init(category: "gratitude", text: "What's a way you've become more yourself since loving me?"),
        .init(category: "gratitude", text: "What's your favorite tradition we've accidentally created?"),
        .init(category: "gratitude", text: "What little thing did I do recently that stuck with you?"),
        .init(category: "gratitude", text: "What are you grateful the internet brought into your life?"),
        .init(category: "gratitude", text: "What's a comfort food that feels like a hug?"),
        .init(category: "gratitude", text: "What's a teacher or mentor you're grateful for?"),
        .init(category: "gratitude", text: "What's the sweetest text I've ever sent you?")
    ]

    static func nextUnasked(excluding history: [String]) -> BankQuestion {
        let pool = all.filter { !history.contains($0.text) }
        if pool.isEmpty {
            return all.randomElement() ?? all[0]
        }
        return pool.randomElement() ?? pool[0]
    }

    static func byCategory(_ category: String, excluding history: [String]) -> BankQuestion? {
        let pool = all.filter { $0.category == category && !history.contains($0.text) }
        return pool.randomElement()
    }
}
